-- DEPRECATED — not needed. The gear "dismiss" feature was replaced by a
-- client-side "Give me more suggestions" button, which requires no database
-- changes. Safe to delete this file (git rm supabase_dismissed_gear.sql).
-- If you already ran it, the unused dismissed_gear column on user_profiles
-- is harmless and can be left in place.
