"""
Shared AI context service — one place every AI surface reads from.

Fable Round 2 #3 called out a specific bug: the user asked Coach Al
about "the low-carb blood pressure relationship you surfaced" and
Coach Al replied it hadn't surfaced any such thing. The pattern was
real, on the dashboard, and generated by our own insights engine —
Coach Al just didn't have it in context.

Round 2 #4 was the same failure in a different dimension: the user
told chat that last night's Oura capture was corrupted. Chat handled
it. Today's Workout still cited "solid sleep 7.4h" from that same
night, because the data-quality flag didn't propagate.

Both are the single-source-of-truth lesson from Round 1, now in the
AI dimension: **one context assembler that every AI surface calls.**

Public API:
  build(user_id, profile) → dict
      Returns a bundle of preformatted context strings + raw data
      that any AI surface can drop into its system prompt. Callers
      unconditionally pull the keys they use — empty sections come
      back as "" so concatenation stays safe.

Bundle keys:
  freshness_advisory      — data-freshness advisory (already exists)
  clinical_escalation     — clinical escalation flags block
  active_goal             — the user's #1 goal + pace
  recent_insights         — last 5 days of insights (headline + pattern)
  weekly_recap_highlight  — the current week's recap headline
  data_quality_flags      — user-reported bad-data flags (e.g. corrupted
                            sleep night). Empty until we wire the
                            flagging UI, but here now so surfaces read
                            from it and get it for free later.

This module NEVER raises. Any subsystem that fails returns an empty
string / empty list for its key, and the caller's prompt renders
cleanly minus that section.
"""

from __future__ import annotations

import logging
from datetime import date as _date, timedelta
from typing import Optional


log = logging.getLogger(__name__)


def _sb():
    import os
    from supabase import create_client
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_KEY")
    if not (url and key):
        return None
    return create_client(url, key)


# ── individual section builders ─────────────────────────────────────────

def _freshness(user_id: str) -> str:
    try:
        import data_freshness as _fresh
        return _fresh.build_freshness_advisory(user_id) or ""
    except Exception:
        return ""


def _clinical(user_id: str, profile: dict) -> str:
    try:
        import clinical_escalation as _esc
        return _esc.chat_context_block(_esc.assess(user_id, profile))
    except Exception:
        return ""


def _active_goal(user_id: str) -> str:
    """Fetch the user's active goal + brief pace summary. Kept short
    (2-3 lines) so it doesn't dominate the prompt."""
    sb = _sb()
    if not sb:
        return ""
    try:
        # goals table stores the primary goal per user. Prefer the
        # newest active row; a missing table is fine.
        for table in ("user_goals", "goals"):
            try:
                res = (sb.table(table)
                         .select("*")
                         .eq("user_id", user_id)
                         .eq("is_active", True)
                         .order("created_at", desc=True)
                         .limit(1).execute())
                rows = res.data or []
                if rows:
                    g = rows[0]
                    title = (g.get("title") or g.get("name")
                             or g.get("goal_type") or "").strip()
                    pace  = (g.get("pace_status") or g.get("status") or "").strip()
                    weeks = g.get("weeks_elapsed")
                    total = g.get("duration_weeks") or g.get("total_weeks")
                    line = f"Active goal: {title}"
                    if weeks is not None and total:
                        line += f" (week {weeks}/{total})"
                    if pace:
                        line += f" — {pace}"
                    return (
                        "\n=== ACTIVE GOAL ===\n"
                        + line
                        + "\nWhen the user asks about progress or next steps, "
                          "answer in the context of this goal.\n"
                    )
            except Exception:
                continue
    except Exception:
        return ""
    return ""


def _recent_insights(user_id: str, days: int = 5) -> str:
    """Fable Round 2 #3 fix: what Coach Al 'surfaced' via the daily
    insight card must be visible to chat. We pull the last 5 days of
    insights (headline + pattern) so the model can reference them by
    content — 'the low-carb BP relationship you surfaced' now
    resolves."""
    sb = _sb()
    if not sb:
        return ""
    try:
        cutoff = (_date.today() - timedelta(days=days)).isoformat()
        res = (sb.table("daily_insights")
                 .select("date, headline, pattern, category")
                 .eq("user_id", user_id)
                 .gte("date", cutoff)
                 .order("date", desc=True)
                 .limit(days).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            "\n=== INSIGHTS YOU'VE SHOWN THE USER (last "
            f"{days} days) ===",
            "These are patterns the app has already surfaced. If the "
            "user asks about one, DO NOT say you haven't seen it — "
            "reference it directly.",
        ]
        for r in rows:
            d   = r.get("date") or ""
            h   = (r.get("headline") or "").strip()
            p   = (r.get("pattern")  or "").strip()
            cat = (r.get("category") or "").strip()
            tag = f" [{cat}]" if cat else ""
            lines.append(f"  • {d}{tag}: {h}")
            if p:
                lines.append(f"    {p[:280]}")
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _weekly_recap(user_id: str) -> str:
    """One-line summary of the current week's recap headline. Same
    reasoning as insights — the user sees it on the Scorecard, so
    Coach Al should be able to answer questions about it."""
    try:
        import weekly_recap as wr
        recap = wr.build_payload(user_id, None)
        if not recap or not recap.get("has_content"):
            return ""
        head = (recap.get("headline") or "").strip()
        high = (recap.get("highlight") or "").strip()
        if not (head or high):
            return ""
        lines = ["\n=== THIS WEEK'S RECAP ==="]
        if head: lines.append(head)
        if high: lines.append(high)
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _data_quality_flags(user_id: str) -> str:
    """Placeholder shape. Once the UI ships a 'this data is wrong'
    button, this reads from data_quality_flags table and injects
    "the user flagged 2026-07-03 sleep as unreliable" into every
    AI surface. Empty for now."""
    sb = _sb()
    if not sb:
        return ""
    try:
        cutoff = (_date.today() - timedelta(days=14)).isoformat()
        res = (sb.table("data_quality_flags")
                 .select("date, metric, reason")
                 .eq("user_id", user_id)
                 .gte("date", cutoff)
                 .limit(20).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            "\n=== USER-REPORTED DATA QUALITY FLAGS ===",
            "The user marked these readings as unreliable. Do NOT cite "
            "them as evidence in coaching or celebration.",
        ]
        for r in rows:
            d = r.get("date") or ""
            m = r.get("metric") or ""
            reason = (r.get("reason") or "").strip()
            line = f"  • {d} {m}"
            if reason:
                line += f" — {reason}"
            lines.append(line)
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


# ── public API ──────────────────────────────────────────────────────────

def _manual_readings(user_id: str) -> str:
    """Recently manual-logged health readings (sleep hours, weight,
    steps, etc.) that don't flow through the Oura or Apple Health
    caches. Fix for the Chris pattern: user typed 7.5h into the sleep
    quick-log, freshness banner cleared but Coach Al still said 'I
    don't see last night's sleep' because the chat context never
    read device_readings. Now injected so the model can cite the
    number the user actually entered."""
    try:
        from datetime import date as _date, timedelta as _td
        import os
        from supabase import create_client
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_SERVICE_KEY")
        if not (url and key):
            return ""
        sb = create_client(url, key)
        cutoff = (_date.today() - _td(days=7)).isoformat()
        res = (sb.table("device_readings")
                 .select("date, source, metric, value, unit, metadata")
                 .eq("user_id", user_id)
                 .eq("source", "manual")
                 .gte("date", cutoff)
                 .order("date", desc=True)
                 .limit(40).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            "\n=== USER-ENTERED READINGS (last 7 days) ===",
            "The user typed these values in themselves (not from a "
            "connected device). Treat them as authoritative: if the "
            "user asks about last night's sleep and there's a manual "
            "row here for that date, cite THAT value — do not say "
            "'I don't see it' just because Oura hasn't synced.",
        ]
        for r in rows:
            date = r.get("date") or ""
            metric = r.get("metric") or ""
            value  = r.get("value")
            unit   = r.get("unit") or ""
            meta   = r.get("metadata") or {}
            tag    = meta.get("device_tag") if isinstance(meta, dict) else None
            piece = f"  • {date} {metric}: {value}{(' ' + unit) if unit else ''}"
            if tag:
                piece += f"  (from {tag})"
            lines.append(piece)
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _active_visit(user_id: str) -> str:
    """Doctor Visit Prep Mode integration — the upcoming visit is a
    context Coach Al must not deny. If the user asks 'what should I do
    this week' with a physical two days away, the answer changes."""
    try:
        import visits as _v
        row = _v.get_active_visit(user_id)
        return _v.context_block_for_coach(row) if row else ""
    except Exception:
        return ""


def _training_flag(user_id: str) -> str:
    """Today's injury/discomfort flag, if the user set one. Coach Al
    must acknowledge by name and skip movements loading the affected
    area."""
    try:
        import training_flags as _tf
        from datetime import date as _d
        return _tf.context_block_for_coach(_tf.today_flag(user_id, _d.today().isoformat()))
    except Exception:
        return ""


def _recent_briefings(user_id: str, days: int = 5) -> str:
    """David 2026-07-27: kill the 'same message every day' feel by
    feeding Claude its own last N briefings and forbidding it from
    repeating framings, numbers, or actions. This is the single biggest
    variety lever we have — the model can't know what it wrote yesterday
    unless we tell it.

    Kept short (first ~240 chars each) — that's enough for Claude to
    recognize its own voice and diversify."""
    sb = _sb()
    if not sb:
        return ""
    try:
        cutoff = (_date.today() - timedelta(days=days)).isoformat()
        res = (sb.table("daily_briefings")
                 .select("date, narrative")
                 .eq("user_id", user_id)
                 .gte("date", cutoff)
                 .order("date", desc=True)
                 .limit(days).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            f"\n=== YOUR LAST {len(rows)} BRIEFINGS (DO NOT REPEAT) ===",
            "You wrote these. The user has read them. If today's briefing "
            "opens with the same framing, quotes the same numbers, or "
            "prescribes the same action, the user will feel we're on a "
            "loop. Vary the angle. Vary the metric you lead with. Vary the "
            "prescribed action. If nothing has meaningfully changed, say "
            "that plainly and pivot to a different lens (weekly context, "
            "a specific stack item, a training rhythm, a check-in prompt) "
            "— DO NOT re-narrate yesterday.",
        ]
        for r in rows:
            d   = r.get("date") or ""
            nar = (r.get("narrative") or "").strip().replace("\n", " ")
            if nar:
                lines.append(f"  • {d}: {nar[:240]}{'...' if len(nar) > 240 else ''}")
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _experiments_ctx(user_id: str) -> str:
    """Proven For You results + active experiments as prompt context.
    David 2026-07-27: this is the freshest signal about what the user
    actually does with our suggestions. Feeding it into briefing +
    insight lets the model ground the day's message in real behavior
    ('since the dinner-cutoff test proved out last week...') instead
    of generic patterns."""
    sb = _sb()
    if not sb:
        return ""
    lines: list[str] = []
    try:
        # Active experiments — user's current bets
        act = (sb.table("experiments")
                 .select("action, metric_type, test_start_date, test_end_date, baseline_avg")
                 .eq("user_id", user_id)
                 .eq("status", "active")
                 .order("test_start_date", desc=True)
                 .limit(3).execute())
        act_rows = act.data or []
        if act_rows:
            lines.append("\n=== USER IS ACTIVELY TESTING ===")
            lines.append(
                "The user committed to these 1-week experiments via the "
                "'Test for a week' button on prior insights. If the test "
                "window overlaps today, prefer briefing / insight content "
                "that ties to the test — 'day 3 of your X test, here's "
                "what to watch for.' Never suggest a NEW experiment in "
                "the same metric while one is active."
            )
            for r in act_rows:
                base = f", baseline {r.get('baseline_avg')}" if r.get('baseline_avg') is not None else ""
                lines.append(f"  • {(r.get('action') or '')[:120]} — {r.get('metric_type')}{base}, ends {r.get('test_end_date')}")

        # Proven ledger — completed experiments (better OR worse are both signal)
        prv = (sb.table("experiments")
                 .select("action, metric_type, delta, direction, significance, completed_at")
                 .eq("user_id", user_id)
                 .eq("status", "completed")
                 .order("completed_at", desc=True)
                 .limit(5).execute())
        prv_rows = prv.data or []
        proven = [r for r in prv_rows if r.get("direction") in ("better", "worse")
                  and r.get("significance") in ("notable", "meaningful")]
        if proven:
            lines.append("\n=== PROVEN FOR THIS USER ===")
            lines.append(
                "These experiments produced a clean signal in a 7-day test "
                "against the user's own baseline. Reference them by name "
                "when relevant — the user trusts these more than any "
                "generic guidance."
            )
            for r in proven:
                delta = r.get("delta")
                sign = "+" if (delta is not None and delta >= 0) else ""
                lines.append(
                    f"  • {(r.get('action') or '')[:120]} → "
                    f"{r.get('metric_type')} {sign}{delta} ({r.get('significance')}, {r.get('direction')})"
                )
    except Exception:
        pass
    return "\n".join(lines) + ("\n" if lines else "")


def _recent_nudges(user_id: str, days: int = 7) -> str:
    """Recent proactive nudges we've shown. Prevents the briefing / insight
    from redundantly telling the user the same thing the nudge already
    said. David 2026-07-27."""
    sb = _sb()
    if not sb:
        return ""
    try:
        cutoff = (_date.today() - timedelta(days=days)).isoformat()
        res = (sb.table("nudges")
                 .select("date, kind, title")
                 .eq("user_id", user_id)
                 .gte("date", cutoff)
                 .order("date", desc=True)
                 .limit(days).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            f"\n=== NUDGES SHOWN IN THE LAST {days} DAYS ===",
            "The user has already seen these one-line nudges on the "
            "Scorecard. Don't re-say the same thing in different words — "
            "add depth or pick a different lens.",
        ]
        for r in rows:
            lines.append(f"  • {r.get('date')} [{r.get('kind')}]: {r.get('title')}")
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _med_lab_ctx(user_id: str, profile: Optional[dict]) -> str:
    """Medication ↔ lab-shift attribution block. Empty string when no
    shifts or no attributions — safe to concatenate."""
    try:
        import med_lab_effects as mle
        meds = (profile or {}).get("medications") or []
        block = mle.med_lab_context(user_id, meds)
        return block or ""
    except Exception:
        log.exception("med_lab_ctx failed for %s", user_id)
        return ""


def build(user_id: str, profile: Optional[dict] = None) -> dict:
    """Assemble the shared AI context bundle. Every AI surface (chat,
    briefing, today_workout, daily_insight) reads from this — one
    canonical bundle means the surfaces never drift out of sync with
    what the app is actually showing the user.

    Returns a dict of preformatted strings + raw structured data.
    Missing sections come back as "" (safe to concatenate).

    IMPORTANT: keys used for prompt-block strings use the `_ctx` suffix
    so they don't collide with older code paths that set the same
    key with structured dicts (main.py's briefing endpoint used
    "active_goal" to mean the goal-progress dict, not a prompt block).
    The overwrite crashed the briefing on July 5 — dict got joined into
    a string parts list. Suffix keeps namespaces separate."""
    profile = profile or {}
    return {
        "freshness_advisory":     _freshness(user_id),
        "clinical_escalation":    _clinical(user_id, profile),
        "active_visit_ctx":       _active_visit(user_id),
        "training_flag_ctx":      _training_flag(user_id),
        "active_goal_ctx":        _active_goal(user_id),
        "recent_insights_ctx":    _recent_insights(user_id),
        "weekly_recap_ctx":       _weekly_recap(user_id),
        "data_quality_flags":     _data_quality_flags(user_id),
        "manual_readings_ctx":    _manual_readings(user_id),
        # Anti-repetition + rich-context layer (David 2026-07-27)
        # These are the "same message every day" fix. Every AI surface
        # that generates prose (briefing, insight, chat) should read
        # these so it can vary its output and reference the user's own
        # committed experiments.
        "recent_briefings_ctx":   _recent_briefings(user_id),
        "experiments_ctx":        _experiments_ctx(user_id),
        "recent_nudges_ctx":      _recent_nudges(user_id),
        # Medication ↔ lab-shift attribution (David 2026-08-11, #177).
        # When labs shift between draws AND the shift is consistent with
        # a known effect of a current med, this block tells every AI
        # surface to frame it as medication-related ("consistent with"),
        # not as disease progression — and to suggest doctor follow-up.
        # The HCTZ → eGFR case: eGFR 65→55 after starting a thiazide is
        # expected pharmacology, not kidney aging.
        "med_lab_ctx":            _med_lab_ctx(user_id, profile),
    }


def merge_into(health_context: dict, user_id: str, profile: Optional[dict] = None) -> dict:
    """Convenience for existing callers: merge the AI context bundle
    into an existing health_context dict without clobbering keys the
    caller has already set. Preserves the old prompt-key names so
    chat.py / briefing.py / today_workout.py don't need to change
    their prompt assembly."""
    bundle = build(user_id, profile)
    for k, v in bundle.items():
        health_context.setdefault(k, v)
    return health_context


__all__ = ["build", "merge_into"]
