"""
Shared AI context service — one place every AI surface reads from.

Fable Round 2 #3 called out a specific bug: the user asked Coach Al
about "the low-carb blood pressure relationship you surfaced" and
Coach Al replied it hadn't surfaced any such thing. The pattern was
real, on the dashboard, and generated by our own insights engine —
Coach Al just didn't have it in context.

Round 2 #4 was the same failure in a different dimension: the user
told chat that last night's Oura capture was corrupted. Chat handled
it. Today's Workout still cited "solid sleep 7.4h" from that same
night, because the data-quality flag didn't propagate.

Both are the single-source-of-truth lesson from Round 1, now in the
AI dimension: **one context assembler that every AI surface calls.**

Public API:
  build(user_id, profile) → dict
      Returns a bundle of preformatted context strings + raw data
      that any AI surface can drop into its system prompt. Callers
      unconditionally pull the keys they use — empty sections come
      back as "" so concatenation stays safe.

Bundle keys:
  freshness_advisory      — data-freshness advisory (already exists)
  clinical_escalation     — clinical escalation flags block
  active_goal             — the user's #1 goal + pace
  recent_insights         — last 5 days of insights (headline + pattern)
  weekly_recap_highlight  — the current week's recap headline
  data_quality_flags      — user-reported bad-data flags (e.g. corrupted
                            sleep night). Empty until we wire the
                            flagging UI, but here now so surfaces read
                            from it and get it for free later.

This module NEVER raises. Any subsystem that fails returns an empty
string / empty list for its key, and the caller's prompt renders
cleanly minus that section.
"""

from __future__ import annotations

import logging
from datetime import date as _date, timedelta
from typing import Optional


log = logging.getLogger(__name__)


def _sb():
    import os
    from supabase import create_client
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_KEY")
    if not (url and key):
        return None
    return create_client(url, key)


# ── individual section builders ─────────────────────────────────────────

def _freshness(user_id: str) -> str:
    try:
        import data_freshness as _fresh
        return _fresh.build_freshness_advisory(user_id) or ""
    except Exception:
        return ""


def _clinical(user_id: str, profile: dict) -> str:
    try:
        import clinical_escalation as _esc
        return _esc.chat_context_block(_esc.assess(user_id, profile))
    except Exception:
        return ""


def _active_goal(user_id: str) -> str:
    """Fetch the user's active goal + brief pace summary. Kept short
    (2-3 lines) so it doesn't dominate the prompt."""
    sb = _sb()
    if not sb:
        return ""
    try:
        # goals table stores the primary goal per user. Prefer the
        # newest active row; a missing table is fine.
        for table in ("user_goals", "goals"):
            try:
                res = (sb.table(table)
                         .select("*")
                         .eq("user_id", user_id)
                         .eq("is_active", True)
                         .order("created_at", desc=True)
                         .limit(1).execute())
                rows = res.data or []
                if rows:
                    g = rows[0]
                    title = (g.get("title") or g.get("name")
                             or g.get("goal_type") or "").strip()
                    pace  = (g.get("pace_status") or g.get("status") or "").strip()
                    weeks = g.get("weeks_elapsed")
                    total = g.get("duration_weeks") or g.get("total_weeks")
                    line = f"Active goal: {title}"
                    if weeks is not None and total:
                        line += f" (week {weeks}/{total})"
                    if pace:
                        line += f" — {pace}"
                    return (
                        "\n=== ACTIVE GOAL ===\n"
                        + line
                        + "\nWhen the user asks about progress or next steps, "
                          "answer in the context of this goal.\n"
                    )
            except Exception:
                continue
    except Exception:
        return ""
    return ""


def _recent_insights(user_id: str, days: int = 5) -> str:
    """Fable Round 2 #3 fix: what Coach Al 'surfaced' via the daily
    insight card must be visible to chat. We pull the last 5 days of
    insights (headline + pattern) so the model can reference them by
    content — 'the low-carb BP relationship you surfaced' now
    resolves."""
    sb = _sb()
    if not sb:
        return ""
    try:
        cutoff = (_date.today() - timedelta(days=days)).isoformat()
        res = (sb.table("daily_insights")
                 .select("date, headline, pattern, category")
                 .eq("user_id", user_id)
                 .gte("date", cutoff)
                 .order("date", desc=True)
                 .limit(days).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            "\n=== INSIGHTS YOU'VE SHOWN THE USER (last "
            f"{days} days) ===",
            "These are patterns the app has already surfaced. If the "
            "user asks about one, DO NOT say you haven't seen it — "
            "reference it directly.",
        ]
        for r in rows:
            d   = r.get("date") or ""
            h   = (r.get("headline") or "").strip()
            p   = (r.get("pattern")  or "").strip()
            cat = (r.get("category") or "").strip()
            tag = f" [{cat}]" if cat else ""
            lines.append(f"  • {d}{tag}: {h}")
            if p:
                lines.append(f"    {p[:280]}")
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _weekly_recap(user_id: str) -> str:
    """One-line summary of the current week's recap headline. Same
    reasoning as insights — the user sees it on the Scorecard, so
    Coach Al should be able to answer questions about it."""
    try:
        import weekly_recap as wr
        recap = wr.build_payload(user_id, None)
        if not recap or not recap.get("has_content"):
            return ""
        head = (recap.get("headline") or "").strip()
        high = (recap.get("highlight") or "").strip()
        if not (head or high):
            return ""
        lines = ["\n=== THIS WEEK'S RECAP ==="]
        if head: lines.append(head)
        if high: lines.append(high)
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _data_quality_flags(user_id: str) -> str:
    """Placeholder shape. Once the UI ships a 'this data is wrong'
    button, this reads from data_quality_flags table and injects
    "the user flagged 2026-07-03 sleep as unreliable" into every
    AI surface. Empty for now."""
    sb = _sb()
    if not sb:
        return ""
    try:
        cutoff = (_date.today() - timedelta(days=14)).isoformat()
        res = (sb.table("data_quality_flags")
                 .select("date, metric, reason")
                 .eq("user_id", user_id)
                 .gte("date", cutoff)
                 .limit(20).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            "\n=== USER-REPORTED DATA QUALITY FLAGS ===",
            "The user marked these readings as unreliable. Do NOT cite "
            "them as evidence in coaching or celebration.",
        ]
        for r in rows:
            d = r.get("date") or ""
            m = r.get("metric") or ""
            reason = (r.get("reason") or "").strip()
            line = f"  • {d} {m}"
            if reason:
                line += f" — {reason}"
            lines.append(line)
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


# ── public API ──────────────────────────────────────────────────────────

def _manual_readings(user_id: str) -> str:
    """Recently manual-logged health readings (sleep hours, weight,
    steps, etc.) that don't flow through the Oura or Apple Health
    caches. Fix for the Chris pattern: user typed 7.5h into the sleep
    quick-log, freshness banner cleared but Coach Al still said 'I
    don't see last night's sleep' because the chat context never
    read device_readings. Now injected so the model can cite the
    number the user actually entered."""
    try:
        from datetime import date as _date, timedelta as _td
        import os
        from supabase import create_client
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_SERVICE_KEY")
        if not (url and key):
            return ""
        sb = create_client(url, key)
        cutoff = (_date.today() - _td(days=7)).isoformat()
        res = (sb.table("device_readings")
                 .select("date, source, metric, value, unit, metadata")
                 .eq("user_id", user_id)
                 .eq("source", "manual")
                 .gte("date", cutoff)
                 .order("date", desc=True)
                 .limit(40).execute())
        rows = res.data or []
        if not rows:
            return ""
        lines = [
            "\n=== USER-ENTERED READINGS (last 7 days) ===",
            "The user typed these values in themselves (not from a "
            "connected device). Treat them as authoritative: if the "
            "user asks about last night's sleep and there's a manual "
            "row here for that date, cite THAT value — do not say "
            "'I don't see it' just because Oura hasn't synced.",
        ]
        for r in rows:
            date = r.get("date") or ""
            metric = r.get("metric") or ""
            value  = r.get("value")
            unit   = r.get("unit") or ""
            meta   = r.get("metadata") or {}
            tag    = meta.get("device_tag") if isinstance(meta, dict) else None
            piece = f"  • {date} {metric}: {value}{(' ' + unit) if unit else ''}"
            if tag:
                piece += f"  (from {tag})"
            lines.append(piece)
        return "\n".join(lines) + "\n"
    except Exception:
        return ""


def _active_visit(user_id: str) -> str:
    """Doctor Visit Prep Mode integration — the upcoming visit is a
    context Coach Al must not deny. If the user asks 'what should I do
    this week' with a physical two days away, the answer changes."""
    try:
        import visits as _v
        row = _v.get_active_visit(user_id)
        return _v.context_block_for_coach(row) if row else ""
    except Exception:
        return ""


def _training_flag(user_id: str) -> str:
    """Today's injury/discomfort flag, if the user set one. Coach Al
    must acknowledge by name and skip movements loading the affected
    area."""
    try:
        import training_flags as _tf
        from datetime import date as _d
        return _tf.context_block_for_coach(_tf.today_flag(user_id, _d.today().isoformat()))
    except Exception:
        return ""


def build(user_id: str, profile: Optional[dict] = None) -> dict:
    """Assemble the shared AI context bundle. Every AI surface (chat,
    briefing, today_workout, daily_insight) reads from this — one
    canonical bundle means the surfaces never drift out of sync with
    what the app is actually showing the user.

    Returns a dict of preformatted strings + raw structured data.
    Missing sections come back as "" (safe to concatenate).

    IMPORTANT: keys used for prompt-block strings use the `_ctx` suffix
    so they don't collide with older code paths that set the same
    key with structured dicts (main.py's briefing endpoint used
    "active_goal" to mean the goal-progress dict, not a prompt block).
    The overwrite crashed the briefing on July 5 — dict got joined into
    a string parts list. Suffix keeps namespaces separate."""
    profile = profile or {}
    return {
        "freshness_advisory":     _freshness(user_id),
        "clinical_escalation":    _clinical(user_id, profile),
        "active_visit_ctx":       _active_visit(user_id),
        "training_flag_ctx":      _training_flag(user_id),
        "active_goal_ctx":        _active_goal(user_id),
        "recent_insights_ctx":    _recent_insights(user_id),
        "weekly_recap_ctx":       _weekly_recap(user_id),
        "data_quality_flags":     _data_quality_flags(user_id),
        "manual_readings_ctx":    _manual_readings(user_id),
    }


def merge_into(health_context: dict, user_id: str, profile: Optional[dict] = None) -> dict:
    """Convenience for existing callers: merge the AI context bundle
    into an existing health_context dict without clobbering keys the
    caller has already set. Preserves the old prompt-key names so
    chat.py / briefing.py / today_workout.py don't need to change
    their prompt assembly."""
    bundle = build(user_id, profile)
    for k, v in bundle.items():
        health_context.setdefault(k, v)
    return health_context


__all__ = ["build", "merge_into"]
