"""
Coach Al's Morning Briefing — a once-per-day narrative for the user.

Where chat.py answers questions on demand, this module produces a *proactive*
note that the user reads at the top of the dashboard each morning. It is
generated by the same Claude Haiku model and uses the same shape of health
context, but the prompt is tuned for a 2–3 paragraph synthesis rather than a
chat reply.

Cache strategy lives in the route handler (main.py): one row per
(user_id, date) in public.daily_briefings.
"""

import os
from typing import Optional


def _build_system_prompt(
    health_context: dict,
    profile: dict,
    prediction_status: Optional[dict],
    yesterday_mood: Optional[str] = None,
    briefing_type: Optional[str] = None,
    type_ctx:      Optional[dict] = None,
) -> str:
    """Build the system prompt for the morning briefing.

    Args mirror chat._build_system_prompt with two additions:
      prediction_status: optional dict with keys streak (int), accuracy_pct (int|None),
                         last_predicted (int|None), last_actual (int|None).
      briefing_type / type_ctx (Layer 2, David 2026-07-27): if provided,
                         a type-specific overlay is appended to the base
                         prompt after all other blocks. See briefing_types
                         module for the type keys and their overlays.
    """
    parts: list[str] = []

    parts.append(
        "You are Coach Al, the personal AI health coach inside the BackNine app. "
        "You are writing the user's MORNING BRIEFING — a short, direct, specific note "
        "they will read at the top of their dashboard when they open the app today. "
        "This is not a chat reply; it is a proactive synthesis of what their body did "
        "last night and what to do about it today.\n\n"
        "WHO YOU ARE WRITING FOR (David 2026-07-23, Fable competitive brief): "
        "adults 50+, often on daily medications, already have a doctor, already read "
        "the news. Direct, no hype, no exclamation points, no 'amazing job' talk. "
        "Longevity math over vanity math (HRV, sleep quality, BP over aesthetic body "
        "comp). Assume the reader is sophisticated; don't over-explain.\n\n"
        "VARY YOUR OUTPUT — CRITICAL (David 2026-07-27):\n"
        "You will see YOUR OWN last few briefings below in a block labeled "
        "'YOUR LAST N BRIEFINGS'. Read them carefully. If today's data is "
        "similar to recent days, the briefing must NOT open with the same "
        "framing, quote the same numbers, or prescribe the same action as "
        "any of those recent briefings. Rotate what you lead with (last "
        "night's number, a 7-day trend, an experiment in progress, a "
        "specific stack item, a training rhythm). If the user is running "
        "an active experiment (see 'USER IS ACTIVELY TESTING' block), "
        "tie today's briefing to that test — day-of, what to watch for. "
        "If they have a Proven For You result (see 'PROVEN FOR THIS "
        "USER'), reference it by name when it's relevant — the user "
        "trusts those more than generic guidance. If nothing has "
        "meaningfully changed and nothing new to say, be honest about "
        "that in one sentence and pivot to a different lens rather than "
        "re-narrating yesterday.\n\n"
        "FORMAT REQUIREMENTS:\n"
        "• Exactly 2 short paragraphs. Total 60–110 words.\n"
        "• Paragraph 1 = What happened. Lead with the most notable change since yesterday. "
        "Cite one or two specific numbers.\n"
        "• Paragraph 2 = What to do. Give ONE specific action for today. "
        "Tie it to the data in paragraph 1.\n"
        "• Address the user by first name once if you have one. Warm but not gushy.\n"
        "• Do not use lists, bullets, or markdown. Plain prose only.\n"
        "• Do not greet with 'Good morning' — the UI already does that.\n"
        "• Do not sign off as 'Coach Al' — the UI shows the avatar.\n"
        "• If data is missing, say so briefly and pivot to what IS known. Never invent numbers.\n"
        "\n"
        "HARD PROHIBITIONS — VIOLATING ANY OF THESE IS A FAILED BRIEFING:\n"
        "1. NEVER ask the user a question. This is a delivery, not a "
        "conversation. Do NOT write 'Which would you prefer?' or "
        "'Want me to focus on X or Y?' or 'Let me know if…'. If you "
        "would otherwise ask, just pick the more useful path and "
        "write it. The user came to READ, not answer.\n"
        "2. NEVER expose internal system machinery. Do NOT say "
        "'briefing type', 'lab focus', 'payload', 'context', "
        "'system prompt', 'template', 'freshness advisory', or "
        "reference any block name shown above. The user does not "
        "know these exist and shouldn't. If a template's premise "
        "can't be fulfilled from the data you have, SILENTLY pivot "
        "to what you can say — never explain that a pivot happened.\n"
        "3. NEVER narrate the data plumbing. Do NOT say 'your Apple "
        "Health hasn't synced', 'Oura tip: tap the sync arrow', "
        "'your detailed session hasn't published', 'data is over "
        "48 hours old', or anything similar. If data is genuinely "
        "stale (>48h), acknowledge it in ONE short clause like 'I "
        "haven't seen fresh Oura data in a few days' and immediately "
        "pivot to a useful action based on trends, habits, or their "
        "stack — not on the sync problem itself.\n"
        "4. NEVER hedge with weasel copy. No 'here's what I'm reading', "
        "'based on what I have', 'solid bookends', 'sounds like', "
        "'may want to consider'. Direct, declarative, specific.\n"
        "5. NEVER quote implausible numbers. If a metric looks "
        "obviously wrong (sleep > 12h, steps > 25k, HRV = 0), "
        "silently drop it and use what's plausible. Don't call "
        "attention to the anomaly."
    )

    # Data-freshness advisory — same block chat.py uses. Placed BEFORE the
    # actual data sections so the model sees staleness state first and
    # can adapt every downstream sentence.
    freshness_advisory = health_context.get("freshness_advisory")
    if freshness_advisory:
        parts.append(freshness_advisory)

    # Fable Round 2 #2/#3/#4 — shared AI context blocks. Clinical
    # escalation flags MUST be surfaced honestly in the briefing (they
    # can't be reframed as lifestyle tweaks). Recent insights and the
    # active goal give the briefing continuity with what the app has
    # already told the user this week.
    # Prompt-block context keys — _ctx suffix keeps them from colliding
    # with the older health_context keys (main.py's briefing endpoint
    # sets active_goal = <dict>; if we read that here and tried to
    # "\n".join() it into parts, we crash with TypeError. This was the
    # July-5 briefing outage.) `isinstance(str)` guard is belt-and-braces.
    for key in ("clinical_escalation", "data_quality_flags", "training_flag_ctx",
                "manual_readings_ctx", "active_visit_ctx", "active_goal_ctx",
                "recent_insights_ctx", "weekly_recap_ctx",
                # Anti-repetition + fresh-behavior blocks (David 2026-07-27).
                # These MUST make it into the prompt or the model can't
                # vary its output and can't reference the user's Proven
                # For You / active experiments.
                "recent_briefings_ctx", "experiments_ctx", "recent_nudges_ctx",
                # Med ↔ lab attribution (David 2026-08-11, #177) — makes
                # the briefing frame med-consistent lab shifts correctly.
                "med_lab_ctx"):
        block = health_context.get(key)
        if isinstance(block, str) and block:
            parts.append(block)

    # User Profile (keep brief — the model already has lots to work with)
    name = profile.get("name", "")
    age = profile.get("age")
    sex = profile.get("biological_sex")
    goals = profile.get("health_goals", [])

    parts.append("\n=== USER ===")
    if name:
        parts.append(f"First name: {name}")
    if age:
        parts.append(f"Age: {age}")
    if sex:
        parts.append(f"Biological sex: {sex}")
    if goals:
        parts.append(f"Goals: {', '.join(goals)}")

    # Static supplement stack — so Coach Al can reference what the user is on
    # when timing/dosing ties to today's recommendation. He must NOT recommend
    # new supplements; the prompt below permits reference only.
    supplements = profile.get("supplements") or []
    if isinstance(supplements, list) and supplements:
        names: list[str] = []
        for s in supplements[:30]:
            if not isinstance(s, dict):
                continue
            nm = (s.get("name") or "").strip()
            if nm:
                bits = [nm]
                if s.get("dose"):   bits.append(str(s["dose"]).strip())
                if s.get("timing"): bits.append(f"({str(s['timing']).strip()})")
                names.append(" ".join(bits))
        if names:
            parts.append("Supplement stack: " + ", ".join(names))
            parts.append(
                "  (You MAY reference these by name if timing/dosing ties to today's plan. "
                "Do NOT recommend NEW supplements. Always use the metric's stated unit.)"
            )

    today = health_context.get("today") or {}
    if today:
        parts.append("\n=== TODAY ===")
        for label, key, unit in [
            ("Readiness", "readiness_score", "/100"),
            ("Sleep score", "sleep_score", "/100"),
            ("HRV", "hrv", " ms"),
            ("Resting HR", "rhr", " bpm"),
            # Activity reflects the just-completed day, not today in progress — at
            # morning briefing time today's activity is near-zero. Coach Al should
            # frame these as yesterday's totals, not today's.
            ("Activity score (yesterday)", "activity_score", "/100"),
            ("Steps (yesterday)", "steps", ""),
            ("Sleep duration", "sleep_hours", " h"),
            ("Body fat", "body_fat_percentage", "%"),
        ]:
            v = today.get(key)
            if v is not None:
                if key == "steps":
                    parts.append(f"  • {label}: {int(v):,}")
                elif key == "sleep_hours":
                    parts.append(f"  • {label}: {v:.1f}{unit}")
                else:
                    parts.append(f"  • {label}: {v}{unit}")
        # Guard against hallucinated sleep figures: if last night's detailed
        # sleep (duration/HRV) hasn't synced but we have the score, tell Coach
        # Al not to quote a duration/HRV or borrow the 7-day average as if it
        # were last night. Rewritten 2026-07-09 after David hit the credibility
        # bug: the model was quoting "still syncing" to the user, which read
        # as OUR failure even though the missing data is Oura-side (session
        # detail lags the score by hours on some rings/days). Now the note
        # is framed as an internal directive — work with what's here, don't
        # narrate what isn't.
        if today.get("sleep_hours") is None:
            parts.append(
                "  • INTERNAL DIRECTIVE (do not quote to user): last night's sleep "
                "duration and HRV numbers are not in this payload. This is normal "
                "when Oura's session detail lags the score by a few hours. "
                "Coach the user based ONLY on what IS present (the sleep score, "
                "readiness, and 7-day averages). Do NOT invent a duration or HRV "
                "for last night, do NOT use the 7-day average as if it were last "
                "night, and DO NOT tell the user their data is 'still syncing' "
                "or 'hasn't come through' — that reads as an app failure. If the "
                "user asks about sleep detail specifically, say plainly that "
                "Oura hasn't published last night's session yet and suggest they "
                "open the Oura app to nudge the sync."
            )

    seven = health_context.get("seven_day") or {}
    if seven:
        parts.append("\n=== 7-DAY CONTEXT ===")
        hrv_avg = seven.get("hrv_avg")
        hrv_dir = seven.get("hrv_direction", "stable")
        if hrv_avg is not None:
            parts.append(f"  • HRV avg: {hrv_avg} ms ({hrv_dir})")
        sleep_avg = seven.get("sleep_avg")
        if sleep_avg is not None:
            parts.append(f"  • Sleep avg: {sleep_avg:.1f} h")
        rdy_avg = seven.get("readiness_avg")
        if rdy_avg is not None:
            parts.append(f"  • Readiness avg: {rdy_avg}/100")

    longevity = health_context.get("longevity_score") or {}
    if longevity and longevity.get("score") is not None:
        parts.append("\n=== LONGEVITY ===")
        parts.append(f"  • Score: {longevity['score']}/100 ({longevity.get('grade', '')})")
        bio_delta = longevity.get("biological_age_delta")
        if bio_delta is not None:
            direction = "younger" if bio_delta < 0 else "older"
            parts.append(f"  • Bio age delta: {abs(bio_delta)} yr {direction} than chronological")

    coaching = health_context.get("coaching") or {}
    if coaching.get("short_term"):
        parts.append("\n=== TODAY'S CODED FOCUS ITEMS ===")
        parts.append(f"  {coaching['short_term']}")

    if yesterday_mood:
        # Map our mood codes to natural language Coach Al can echo.
        mood_descriptors = {
            "great": "great",
            "good":  "good",
            "okay":  "okay",
            "tired": "tired",
            "off":   "off / not themselves",
        }
        descriptor = mood_descriptors.get(yesterday_mood, yesterday_mood)
        parts.append("\n=== YESTERDAY'S CHECK-IN ===")
        parts.append(f"  • The user reported feeling {descriptor} yesterday.")
        parts.append(
            "  (You MAY reference this in paragraph 1 if today's metrics either "
            "confirm or contrast with how they felt. Only mention if it adds insight.)"
        )

    goal = health_context.get("active_goal") or {}
    pace = (goal or {}).get("pace") or {}
    if goal and pace and pace.get("status") not in (None, "no_data"):
        unit = (goal.get("unit") or "").strip()
        unit_label = unit if unit else "units"
        unit_fmt   = f" {unit}" if unit and not unit.startswith("%") else (unit or "")
        parts.append("\n=== ACTIVE GOAL ===")
        parts.append(f"  • Metric: {goal.get('label')} (measured in {unit_label})")
        parts.append(
            f"  • Now {goal.get('current')}{unit_fmt} → target {goal.get('target')}{unit_fmt}"
        )
        # Pre-compute the gap with the correct unit so Coach Al just reads it
        # (no risk of "0.6 pounds" when the goal is in %).
        try:
            cur = goal.get("current"); tgt = goal.get("target")
            if cur is not None and tgt is not None:
                gap = round(abs(float(tgt) - float(cur)), 1)
                direction = "above" if float(cur) > float(tgt) else "below" if float(cur) < float(tgt) else "at"
                parts.append(f"  • Distance to target: {gap}{unit_fmt} ({direction} target)")
        except Exception:
            pass
        wk, tw, dl = goal.get("week"), goal.get("total_weeks"), goal.get("days_left")
        if wk and tw:
            parts.append(f"  • Timeline: week {wk} of {tw}, {dl} days left")
        delta = pace.get("delta_pct")
        if delta is not None and pace.get("status") not in ("reached", "starting"):
            parts.append(f"  • Pace: {pace.get('label')} ({delta:+d}% vs expected)")
        else:
            parts.append(f"  • Pace: {pace.get('label')}")
        tw_focus = (goal.get("this_week") or {}).get("focus")
        if tw_focus:
            parts.append(f"  • This week's focus: {tw_focus}")
        parts.append(
            "  (You MAY add ONE short clause about this goal in paragraph 2 — celebrate if "
            "ahead, gently rally if behind — and tie today's action to it. Keep it natural "
            "and skip it if today's data already fills the briefing. Never invent goal numbers. "
            "ALWAYS use the metric's stated unit — body fat is %, weight is pounds, VO2 max "
            "is ml/kg/min. Do NOT substitute pounds for percent or vice versa.)"
        )

    nutrition = health_context.get("nutrition") or {}
    body = health_context.get("body") or {}
    if (nutrition and nutrition.get("meals_logged")) or body.get("weight_lbs") is not None:
        parts.append("\n=== NUTRITION & BODY ===")
        if nutrition and nutrition.get("meals_logged"):
            c = nutrition.get("consumed", {})
            t = nutrition.get("targets", {})
            day = nutrition.get("date")
            bits: list[str] = []
            if c.get("calories") is not None:
                bits.append(f"{c['calories']}{('/' + str(t['calories'])) if t.get('calories') else ''} cal")
            if c.get("protein") is not None:
                bits.append(f"{c['protein']}{('/' + str(t['protein'])) if t.get('protein') else ''}g protein")
            if c.get("carbs") is not None:
                bits.append(f"{c['carbs']}g carbs")
            if c.get("fat") is not None:
                bits.append(f"{c['fat']}g fat")
            if bits:
                parts.append(f"  • Last logged day ({day}): " + ", ".join(bits))
        if body.get("weight_lbs") is not None:
            line = f"  • Weight: {body['weight_lbs']} lbs"
            chg = body.get("change_since_prev_lbs")
            if chg is not None:
                direction = "down" if chg < 0 else "up" if chg > 0 else "flat"
                line += f" ({direction} {abs(chg)} lbs since last weigh-in)"
            parts.append(line)
            if body.get("muscle_mass_lbs") is not None:
                parts.append(f"  • Muscle mass: {body['muscle_mass_lbs']} lbs")
        parts.append(
            "  (You MAY reference nutrition or weight if it's notable or ties to today's "
            "recommendation — e.g., protein ran low yesterday, or weight is trending toward "
            "their goal. Only mention if it adds value. Never invent numbers.)"
        )

    if prediction_status:
        streak = prediction_status.get("streak")
        last_pred = prediction_status.get("last_predicted")
        last_act = prediction_status.get("last_actual")
        if streak or last_pred is not None:
            parts.append("\n=== PREDICTION GAME ===")
            if last_pred is not None and last_act is not None:
                hit = abs(last_act - last_pred) <= 7
                parts.append(
                    f"  • Yesterday's forecast: predicted {last_pred}, actual {last_act} "
                    f"({'hit' if hit else 'miss'})"
                )
            if streak:
                parts.append(f"  • Current streak: {streak} day(s)")
            parts.append(
                "  (You MAY reference the streak in paragraph 2 if it adds energy, "
                "but only if it's at least 3 days. Otherwise skip it.)"
            )

    # Append the shared voice/brand block (golf metaphor allowance) so the
    # briefing inherits the same instructions as every other Coach Al surface.
    from coach_voice import VOICE_BLOCK
    parts.append("\n" + VOICE_BLOCK)

    # Layer 2 (David 2026-07-27): day-type overlay. Appended LAST so it
    # takes precedence over the default 2-paragraph 60-110 word format
    # when the type calls for a different shape (e.g. Sunday recap runs
    # 90-130 words, experiment-progress reframes both paragraphs). The
    # base voice + 50+ rules still apply — overlay is emphasis, not
    # replacement.
    if briefing_type and briefing_type != "default":
        try:
            import briefing_types as _bt
            overlay = _bt.overlay_for(briefing_type, type_ctx or {})
            if overlay:
                parts.append("\n" + overlay)
        except Exception:
            # Silent fallback — default format still works
            pass

    return "\n".join(parts)


def generate(
    health_context: dict,
    profile: dict,
    prediction_status: Optional[dict] = None,
    yesterday_mood: Optional[str] = None,
    briefing_type: Optional[str] = None,
    type_ctx:      Optional[dict] = None,
) -> str:
    """Generate today's morning briefing.

    Returns the narrative text (2 short paragraphs). Caller is responsible
    for caching the result in daily_briefings.

    briefing_type / type_ctx (Layer 2): if provided, a type-specific
    prompt overlay is appended so the briefing takes the right shape
    for the day (Sunday recap, Monday framing, experiment progress,
    lab focus, visit prep). Default when omitted.

    Raises:
        RuntimeError: If ANTHROPIC_API_KEY is not set or anthropic package is missing.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not configured")

    try:
        import anthropic
    except ImportError:
        raise RuntimeError("anthropic package not installed — run: pip install anthropic")

    client = anthropic.Anthropic(api_key=api_key)
    system = _build_system_prompt(
        health_context, profile, prediction_status, yesterday_mood,
        briefing_type=briefing_type, type_ctx=type_ctx,
    )

    # The "user" turn is a meta-instruction — Claude treats it as the prompt to
    # respond to. We don't have anything user-typed; this is a generation task.
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=400,
        system=system,
        messages=[
            {
                "role": "user",
                "content": "Write today's morning briefing now, following the format requirements exactly.",
            }
        ],
    )

    return response.content[0].text.strip()
