"""
Coach Al's Morning Briefing — a once-per-day narrative for the user.

Where chat.py answers questions on demand, this module produces a *proactive*
note that the user reads at the top of the dashboard each morning. It is
generated by the same Claude Haiku model and uses the same shape of health
context, but the prompt is tuned for a 2–3 paragraph synthesis rather than a
chat reply.

Cache strategy lives in the route handler (main.py): one row per
(user_id, date) in public.daily_briefings.
"""

import os
from typing import Optional


def _build_system_prompt(health_context: dict, profile: dict, prediction_status: Optional[dict]) -> str:
    """Build the system prompt for the morning briefing.

    Args mirror chat._build_system_prompt with one addition:
      prediction_status: optional dict with keys streak (int), accuracy_pct (int|None),
                         last_predicted (int|None), last_actual (int|None).
    """
    parts: list[str] = []

    parts.append(
        "You are Coach Al, the personal AI health coach inside the BackNine app. "
        "You are writing the user's MORNING BRIEFING — a short, warm, specific note "
        "they will read at the top of their dashboard when they open the app today. "
        "This is not a chat reply; it is a proactive synthesis of what their body did "
        "last night and what to do about it today.\n\n"
        "FORMAT REQUIREMENTS:\n"
        "• Exactly 2 short paragraphs. Total 60–110 words.\n"
        "• Paragraph 1 = What happened. Lead with the most notable change since yesterday. "
        "Cite one or two specific numbers.\n"
        "• Paragraph 2 = What to do. Give ONE specific action for today. "
        "Tie it to the data in paragraph 1.\n"
        "• Address the user by first name once if you have one. Warm but not gushy.\n"
        "• Do not use lists, bullets, or markdown. Plain prose only.\n"
        "• Do not greet with 'Good morning' — the UI already does that.\n"
        "• Do not sign off as 'Coach Al' — the UI shows the avatar.\n"
        "• If data is missing, say so briefly and pivot to what IS known. Never invent numbers."
    )

    # User Profile (keep brief — the model already has lots to work with)
    name = profile.get("name", "")
    age = profile.get("age")
    sex = profile.get("biological_sex")
    goals = profile.get("health_goals", [])

    parts.append("\n=== USER ===")
    if name:
        parts.append(f"First name: {name}")
    if age:
        parts.append(f"Age: {age}")
    if sex:
        parts.append(f"Biological sex: {sex}")
    if goals:
        parts.append(f"Goals: {', '.join(goals)}")

    today = health_context.get("today") or {}
    if today:
        parts.append("\n=== TODAY ===")
        for label, key, unit in [
            ("Readiness", "readiness_score", "/100"),
            ("Sleep score", "sleep_score", "/100"),
            ("HRV", "hrv", " ms"),
            ("Resting HR", "rhr", " bpm"),
            ("Activity score", "activity_score", "/100"),
            ("Steps", "steps", ""),
            ("Sleep duration", "sleep_hours", " h"),
            ("Body fat", "body_fat_percentage", "%"),
        ]:
            v = today.get(key)
            if v is not None:
                if key == "steps":
                    parts.append(f"  • {label}: {int(v):,}")
                elif key == "sleep_hours":
                    parts.append(f"  • {label}: {v:.1f}{unit}")
                else:
                    parts.append(f"  • {label}: {v}{unit}")

    seven = health_context.get("seven_day") or {}
    if seven:
        parts.append("\n=== 7-DAY CONTEXT ===")
        hrv_avg = seven.get("hrv_avg")
        hrv_dir = seven.get("hrv_direction", "stable")
        if hrv_avg is not None:
            parts.append(f"  • HRV avg: {hrv_avg} ms ({hrv_dir})")
        sleep_avg = seven.get("sleep_avg")
        if sleep_avg is not None:
            parts.append(f"  • Sleep avg: {sleep_avg:.1f} h")
        rdy_avg = seven.get("readiness_avg")
        if rdy_avg is not None:
            parts.append(f"  • Readiness avg: {rdy_avg}/100")

    longevity = health_context.get("longevity_score") or {}
    if longevity and longevity.get("score") is not None:
        parts.append("\n=== LONGEVITY ===")
        parts.append(f"  • Score: {longevity['score']}/100 ({longevity.get('grade', '')})")
        bio_delta = longevity.get("biological_age_delta")
        if bio_delta is not None:
            direction = "younger" if bio_delta < 0 else "older"
            parts.append(f"  • Bio age delta: {abs(bio_delta)} yr {direction} than chronological")

    coaching = health_context.get("coaching") or {}
    if coaching.get("short_term"):
        parts.append("\n=== TODAY'S CODED FOCUS ITEMS ===")
        parts.append(f"  {coaching['short_term']}")

    if prediction_status:
        streak = prediction_status.get("streak")
        last_pred = prediction_status.get("last_predicted")
        last_act = prediction_status.get("last_actual")
        if streak or last_pred is not None:
            parts.append("\n=== PREDICTION GAME ===")
            if last_pred is not None and last_act is not None:
                hit = abs(last_act - last_pred) <= 7
                parts.append(
                    f"  • Yesterday's forecast: predicted {last_pred}, actual {last_act} "
                    f"({'hit' if hit else 'miss'})"
                )
            if streak:
                parts.append(f"  • Current streak: {streak} day(s)")
            parts.append(
                "  (You MAY reference the streak in paragraph 2 if it adds energy, "
                "but only if it's at least 3 days. Otherwise skip it.)"
            )

    return "\n".join(parts)


def generate(
    health_context: dict,
    profile: dict,
    prediction_status: Optional[dict] = None,
) -> str:
    """Generate today's morning briefing.

    Returns the narrative text (2 short paragraphs). Caller is responsible
    for caching the result in daily_briefings.

    Raises:
        RuntimeError: If ANTHROPIC_API_KEY is not set or anthropic package is missing.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not configured")

    try:
        import anthropic
    except ImportError:
        raise RuntimeError("anthropic package not installed — run: pip install anthropic")

    client = anthropic.Anthropic(api_key=api_key)
    system = _build_system_prompt(health_context, profile, prediction_status)

    # The "user" turn is a meta-instruction — Claude treats it as the prompt to
    # respond to. We don't have anything user-typed; this is a generation task.
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=400,
        system=system,
        messages=[
            {
                "role": "user",
                "content": "Write today's morning briefing now, following the format requirements exactly.",
            }
        ],
    )

    return response.content[0].text.strip()
