"""
Coach Al's micro-reactions — one-line reactions fired right after a user
action so the coach feels alive instead of being a once-a-morning ghost.

Trigger points (initial set; more to come):
  • meal logged    → "Solid 38g protein — you're 12g ahead of today's target."
  • workout saved  → "Two days in a row on legs. Recovery walk tomorrow?"
  • weigh-in       → "Down 0.4 lbs since last week — quiet and steady wins."

Each reaction is one short sentence (≤20 words), warm, specific, and ties
to numbers the user just generated. Generated by Haiku — same model as the
briefing — with a very tight prompt that forbids advice essays, lists, or
sign-offs. Failures degrade silently (the action still succeeded).
"""

import os
from typing import Any, Optional


# Action kinds the frontend can request a reaction for. Keep this list small;
# every kind needs prompt language tuned for what's actually informative.
VALID_ACTIONS = {
    "meal_logged",
    "workout_logged",
    "weight_logged",
}


def _system_prompt(action_kind: str) -> str:
    """The prompt is action-specific so Haiku doesn't try to be generic."""
    base = (
        "You are Coach Al, the user's AI health coach in BackNine. The user just "
        "took an action in the app. Your job is to react in ONE SHORT SENTENCE. "
        "This is a real-time reaction, not advice. Like a coach in the room "
        "saying 'nice rep' when they see the bar move.\n\n"
        "STRICT RULES:\n"
        "• Exactly ONE sentence, ≤ 20 words.\n"
        "• Warm but not gushing. Specific, not generic.\n"
        "• Cite at least one specific number from the action when relevant.\n"
        "• Plain prose only — no emoji, no markdown, no lists, no sign-off.\n"
        "• Do not say 'great job' or 'keep it up'. Be specific.\n"
        "• Never invent numbers.\n"
    )
    if action_kind == "meal_logged":
        base += (
            "\nFor meal_logged: react to what they ate vs their daily targets. "
            "If they hit protein, say so. If they're behind on calories, point it out. "
            "If they're eating a big late-day meal, comment on timing. Keep it useful."
        )
    elif action_kind == "workout_logged":
        base += (
            "\nFor workout_logged: react to volume, duration, or type vs recent pattern. "
            "If it's a hard session after a tough sleep, note the courage. "
            "If it's a recovery day, validate the choice. One specific observation."
        )
    elif action_kind == "weight_logged":
        base += (
            "\nFor weight_logged: react to the change vs last weigh-in or the trend. "
            "Steady = celebrate consistency. Down toward goal = note progress. "
            "Up doesn't always mean bad — water, glycogen, life. Be honest, not punishing."
        )
    return base


def _user_payload(action_kind: str, details: dict, profile: dict, goal: Optional[dict]) -> str:
    """Compress what just happened + user state into a tight context block."""
    lines: list[str] = []
    name = (profile or {}).get("name") or "the user"
    lines.append(f"User: {name}")

    if goal:
        lines.append(f"Active goal: {goal.get('label')} → {goal.get('target')} {goal.get('unit') or ''}")
        pace = goal.get("pace") or {}
        if pace.get("label"):
            lines.append(f"Goal pace: {pace.get('label')}")

    lines.append(f"\nAction: {action_kind}")
    if action_kind == "meal_logged":
        meal = details.get("meal") or {}
        totals = details.get("totals") or {}
        targets = details.get("targets") or {}
        if meal.get("name"):
            lines.append(f"  Logged: {meal.get('name')}")
        if meal.get("calories") is not None:
            lines.append(f"  This meal: {meal.get('calories')} kcal · {meal.get('protein', 0)}g protein · {meal.get('carbs', 0)}g carbs · {meal.get('fat', 0)}g fat")
        if totals:
            lines.append(f"  Today so far: {totals.get('calories', 0)} kcal · {totals.get('protein', 0)}g protein · {totals.get('carbs', 0)}g carbs · {totals.get('fat', 0)}g fat")
        if targets:
            lines.append(f"  Daily targets: {targets.get('calories', '—')} kcal · {targets.get('protein', '—')}g protein")
    elif action_kind == "workout_logged":
        w = details.get("workout") or {}
        lines.append(f"  Type: {w.get('type', '—')} · {w.get('duration_min', '?')} min")
        if w.get("total_volume_lbs"):
            lines.append(f"  Volume: {w.get('total_volume_lbs')} lbs")
        if w.get("activity"):
            lines.append(f"  Activity: {w.get('activity')}, {w.get('distance_meters', 0)/1609.34:.2f} mi")
    elif action_kind == "weight_logged":
        entry = details.get("entry") or {}
        prev  = details.get("previous") or {}
        lines.append(f"  Today: {entry.get('weight_lbs', '?')} lbs")
        if entry.get("body_fat_pct") is not None:
            lines.append(f"  Body fat: {entry.get('body_fat_pct')}%")
        if prev.get("weight_lbs") is not None:
            delta = round((entry.get("weight_lbs", 0) - prev.get("weight_lbs", 0)), 1)
            sign  = "+" if delta > 0 else ""
            lines.append(f"  Previous: {prev.get('weight_lbs')} lbs ({sign}{delta} delta)")

    return "\n".join(lines)


def generate_reaction(
    action_kind: str,
    details: dict,
    profile: dict,
    goal: Optional[dict] = None,
) -> Optional[str]:
    """Generate the one-sentence reaction. Returns None if generation fails
    so the calling endpoint can return null silently — the action succeeded
    regardless of whether Coach Al had something witty to say."""
    if action_kind not in VALID_ACTIONS:
        return None
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return None
    try:
        import anthropic
    except ImportError:
        return None
    try:
        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=80,
            system=_system_prompt(action_kind),
            messages=[{
                "role": "user",
                "content": _user_payload(action_kind, details, profile, goal),
            }],
        )
        text = (response.content[0].text or "").strip()
        # Trim quotes / trailing punctuation oddities — the prompt asks for one
        # sentence but Haiku occasionally wraps in quotes.
        if text.startswith('"') and text.endswith('"'):
            text = text[1:-1]
        return text or None
    except Exception:
        return None
