export interface GearItem {
  id: string;
  name: string;
  brand: string;
  description: string;
  price: string;        // e.g. "$29.99" or "$25–$40"
  link: string;         // affiliate or product page URL
  image?: string;       // optional product image URL
  badge?: string;       // e.g. "Editor's Pick", "Popular", "New"
}

export interface GearCategory {
  id: string;
  label: string;
  icon: string;
  items: GearItem[];
}

const GEAR: GearCategory[] = [
  {
    id: "supplements",
    label: "Supplements",
    icon: "💊",
    items: [
      {
        id: "mag-glycinate",
        name: "Magnesium Glycinate",
        brand: "Thorne",
        description: "Supports deep sleep, muscle recovery, and stress response. One of the most bioavailable forms of magnesium.",
        price: "$34",
        link: "https://www.amazon.com/s?k=thorne+magnesium+bisglycinate",
        badge: "Editor's Pick",
      },
      {
        id: "omega3",
        name: "Omega-3 Fish Oil",
        brand: "Nordic Naturals",
        description: "High-potency EPA/DHA for cardiovascular health, inflammation reduction, and cognitive function.",
        price: "$40",
        link: "https://www.amazon.com/s?k=nordic+naturals+ultimate+omega",
      },
      {
        id: "vitamin-d",
        name: "Vitamin D3 + K2",
        brand: "Thorne",
        description: "Essential for immune function, bone density, and mood. K2 ensures calcium goes to bones, not arteries.",
        price: "$28",
        link: "https://www.amazon.com/s?k=thorne+vitamin+d+k2",
      },
      {
        id: "creatine",
        name: "Creatine Monohydrate",
        brand: "Momentous",
        description: "5g daily for strength, power output, and cognitive performance. One of the most researched supplements.",
        price: "$40",
        link: "https://www.livemomentous.com/products/creatine",
        badge: "Popular",
      },
      {
        id: "ashwagandha",
        name: "Ashwagandha (KSM-66)",
        brand: "Nutricost",
        description: "Adaptogen shown to lower cortisol and support stress resilience and sleep onset.",
        price: "$20",
        link: "https://www.amazon.com/s?k=ksm-66+ashwagandha",
      },
      {
        id: "probiotic",
        name: "DS-01 Daily Synbiotic",
        brand: "Seed",
        description: "Clinically-studied probiotic + prebiotic for gut health, digestion, and immune support.",
        price: "$50",
        link: "https://seed.com/ds-01",
      },
    ],
  },
  {
    id: "sleep",
    label: "Sleep",
    icon: "😴",
    items: [
      {
        id: "oura-ring",
        name: "Oura Ring Gen 4",
        brand: "Oura",
        description: "The gold standard for sleep and recovery tracking. Tracks HRV, sleep stages, body temperature, and readiness.",
        price: "$349",
        link: "https://ouraring.com/product/rings/oura-ring-4",
        badge: "Editor's Pick",
      },
      {
        id: "sleep-mask",
        name: "Contoured Sleep Mask",
        brand: "Manta",
        description: "100% blackout, zero eye pressure. Dramatically improves sleep quality in any environment.",
        price: "$35",
        link: "https://www.amazon.com/s?k=manta+sleep+mask",
      },
      {
        id: "magtech",
        name: "MagTech Magnesium Complex",
        brand: "Natural Stacks",
        description: "Three forms of magnesium for relaxation and deep sleep. Take 30 minutes before bed.",
        price: "$39",
        link: "https://www.amazon.com/s?k=natural+stacks+magtech",
      },
      {
        id: "eight-sleep",
        name: "Pod 5",
        brand: "Eight Sleep",
        description: "Active temperature-regulating bed system. Heats and cools each side through the night to improve deep sleep.",
        price: "From $2,849",
        link: "https://www.eightsleep.com/product/pod5ultra/",
        badge: "Editor's Pick",
      },
      {
        id: "hatch-restore",
        name: "Restore 2 Sunrise Alarm",
        brand: "Hatch",
        description: "Sunrise alarm, wind-down routines, and sleep sounds — a gentler wake than a phone alarm.",
        price: "$170",
        link: "https://www.hatch.co/restore",
      },
      {
        id: "mouth-tape",
        name: "Mouth Tape",
        brand: "Hostage Tape",
        description: "Encourages nasal breathing overnight — many users see better sleep quality and lower snoring.",
        price: "$25",
        link: "https://www.amazon.com/s?k=mouth+tape+for+sleeping",
      },
    ],
  },
  {
    id: "recovery",
    label: "Recovery",
    icon: "🔄",
    items: [
      {
        id: "massage-gun",
        name: "Theragun Prime",
        brand: "Therabody",
        description: "Percussive therapy for muscle soreness, tight spots, and post-workout recovery.",
        price: "$249",
        link: "https://www.therabody.com/us/en-us/theragun-prime.html",
      },
      {
        id: "foam-roller",
        name: "Grid Foam Roller",
        brand: "TriggerPoint",
        description: "Multi-density surface for targeted myofascial release. A daily recovery staple.",
        price: "$36",
        link: "https://www.amazon.com/s?k=triggerpoint+grid+foam+roller",
        badge: "Popular",
      },
      {
        id: "sauna-blanket",
        name: "Hydragun Sauna Blanket",
        brand: "Hydragun",
        description: "Infrared sauna at home. Supports detox, recovery, and relaxation without a full sauna setup.",
        price: "$499",
        link: "https://hydragun.com/products/sauna-blanket",
      },
      {
        id: "cold-plunge",
        name: "Ice Barrel 400",
        brand: "Ice Barrel",
        description: "Cold water immersion for inflammation, mental toughness, and post-workout recovery.",
        price: "$1,200",
        link: "https://icebarrel.com",
      },
      {
        id: "compression-boots",
        name: "Normatec 3 Legs",
        brand: "Therabody",
        description: "Dynamic air compression boots that flush the legs after hard training. A pro-athlete recovery staple.",
        price: "$799",
        link: "https://www.therabody.com/us/en-us/normatec-3.html",
      },
      {
        id: "red-light",
        name: "Red Light Therapy Panel",
        brand: "Mito Red Light",
        description: "Red + near-infrared light for muscle recovery, skin, and circulation. 10–15 min sessions.",
        price: "$549",
        link: "https://www.amazon.com/s?k=mito+red+light+panel",
      },
      {
        id: "massage-ball",
        name: "Massage Ball Set",
        brand: "TriggerPoint",
        description: "Pinpoint myofascial release for feet, glutes, and shoulders where a roller can't reach.",
        price: "$20",
        link: "https://www.amazon.com/s?k=triggerpoint+massage+ball",
      },
    ],
  },
  {
    id: "fitness",
    label: "Fitness Equipment",
    icon: "🏋️",
    items: [
      {
        id: "adjustable-dumbbells",
        name: "Adjustable Dumbbells",
        brand: "Bowflex",
        description: "Replace 15 sets of weights. Quick-change dial system from 5 to 52.5 lbs per dumbbell.",
        price: "$429",
        link: "https://www.amazon.com/s?k=bowflex+selecttech+552",
        badge: "Popular",
      },
      {
        id: "pull-up-bar",
        name: "Wall-Mounted Pull-Up Bar",
        brand: "Rogue",
        description: "Sturdy, permanent pull-up station for upper body and core strength. Essential home gym piece.",
        price: "$120",
        link: "https://www.roguefitness.com/p-3-pull-up-bar",
      },
      {
        id: "kettlebell",
        name: "Competition Kettlebell",
        brand: "Titan Fitness",
        description: "Single piece cast iron. Perfect for swings, Turkish get-ups, and full-body conditioning.",
        price: "$65",
        link: "https://www.amazon.com/s?k=titan+competition+kettlebell",
      },
      {
        id: "resistance-bands",
        name: "Resistance Bands Set",
        brand: "Rogue",
        description: "Travel-friendly, full-body strength and mobility work. The most versatile dollar in your gym bag.",
        price: "$30",
        link: "https://www.amazon.com/s?k=resistance+bands+set",
      },
      {
        id: "rower",
        name: "RowErg",
        brand: "Concept2",
        description: "The gold-standard cardio machine — full-body, low-impact, and the most trusted erg in the world.",
        price: "$990",
        link: "https://www.concept2.com/rowergs/model-d",
        badge: "Editor's Pick",
      },
      {
        id: "weighted-vest",
        name: "G-Vest Weighted Vest",
        brand: "OMORPHO",
        description: "Distributed micro-weights add load to walks, rucks, and bodyweight work without bulk — an easy way to raise intensity in the same time.",
        price: "$249",
        link: "https://omorpho.com/products/g-vest",
      },
      {
        id: "jump-rope",
        name: "Speed Jump Rope",
        brand: "Crossrope",
        description: "Compact, high-output conditioning. Two minutes of skipping spikes your heart rate fast.",
        price: "$40",
        link: "https://www.amazon.com/s?k=crossrope+jump+rope",
      },
    ],
  },
  {
    id: "wearables",
    label: "Wearables",
    icon: "⌚",
    items: [
      {
        id: "apple-watch",
        name: "Apple Watch Series 11",
        brand: "Apple",
        description: "The most capable health wearable for iPhone users. ECG, blood oxygen, sleep tracking, and more.",
        price: "$399",
        link: "https://www.apple.com/apple-watch-series-11/",
      },
      {
        id: "inbody-scale",
        name: "InBody H40 Smart Scale",
        brand: "InBody",
        description: "Clinical-grade body composition analysis at home. Measures muscle mass, body fat %, and more. Syncs to Apple Health.",
        price: "$300",
        link: "https://www.amazon.com/s?k=inbody+h40+smart+scale",
        badge: "Editor's Pick",
      },
      {
        id: "whoop",
        name: "WHOOP 5.0",
        brand: "WHOOP",
        description: "Screenless strain and recovery tracker, now with 14+ day battery. Worn 24/7 for continuous HRV, sleep, and recovery data.",
        price: "From $199/yr",
        link: "https://www.whoop.com",
      },
      {
        id: "withings-bp",
        name: "BPM Connect",
        brand: "Withings",
        description: "Clinically-validated blood pressure monitor that syncs to Apple Health — unlocks the BP signal in your Longevity Score.",
        price: "$100",
        link: "https://www.withings.com/us/en/bpm-connect",
        badge: "Editor's Pick",
      },
      {
        id: "garmin-fr165",
        name: "Forerunner 165",
        brand: "Garmin",
        description: "GPS running watch with VO2 max, training load, and multi-week battery — a strong non-Apple option.",
        price: "$250",
        link: "https://www.garmin.com/en-US/p/845658",
      },
      {
        id: "cgm-stelo",
        name: "Stelo Glucose Biosensor",
        brand: "Dexcom",
        description: "Over-the-counter continuous glucose monitor. See how meals, sleep, and stress move your blood sugar.",
        price: "$99/mo",
        link: "https://www.stelo.com",
      },
      {
        id: "polar-h10",
        name: "H10 Heart Rate Sensor",
        brand: "Polar",
        description: "Chest-strap HR monitor — the accuracy benchmark for interval training and Zone 2 work.",
        price: "$90",
        link: "https://www.amazon.com/s?k=polar+h10",
      },
    ],
  },
  {
    id: "lab-work",
    label: "Lab Work",
    icon: "🧪",
    items: [
      {
        id: "function-health",
        name: "Function Health",
        brand: "Function",
        description: "100+ lab biomarkers tested twice a year, clinician-reviewed, on an easy-to-read dashboard. A true whole-body baseline.",
        price: "$499/yr",
        link: "https://www.functionhealth.com",
        badge: "Editor's Pick",
      },
      {
        id: "superpower",
        name: "Superpower Membership",
        brand: "Superpower",
        description: "Annual membership with 100+ lab tests, a longitudinal dashboard, and concierge guidance — a direct Function alternative.",
        price: "$499/yr",
        link: "https://www.superpower.com",
      },
      {
        id: "insidetracker",
        name: "InsideTracker",
        brand: "InsideTracker",
        description: "Blood biomarker analysis with personalized nutrition, supplement, and training recommendations. Strong for athletes optimizing performance.",
        price: "From $179",
        link: "https://www.insidetracker.com",
        badge: "Popular",
      },
      {
        id: "siphox-health",
        name: "At-Home Blood Testing",
        brand: "SiPhox Health",
        description: "Finger-prick blood testing you do at home — no lab visit. Track key biomarkers on a subscription.",
        price: "From $95",
        link: "https://siphoxhealth.com",
      },
      {
        id: "quest-health",
        name: "Quest Health",
        brand: "Quest Diagnostics",
        description: "Order your own lab tests online and visit a Quest location for the draw. Pay per test, no doctor referral needed.",
        price: "Per test",
        link: "https://www.questhealth.com",
      },
      {
        id: "labcorp-ondemand",
        name: "Labcorp OnDemand",
        brand: "Labcorp",
        description: "Direct-to-consumer lab tests from a major national lab. Buy online, get tested at a Labcorp site, see results in your portal.",
        price: "Per test",
        link: "https://www.ondemand.labcorp.com",
      },
      {
        id: "everlywell",
        name: "At-Home Test Kits",
        brand: "Everlywell",
        description: "Mail-in test kits for thyroid, metabolism, vitamins, and more — collect a sample at home and send it in.",
        price: "From $49",
        link: "https://www.everlywell.com",
      },
    ],
  },
  {
    id: "nutrition",
    label: "Nutrition",
    icon: "🥤",
    items: [
      {
        id: "whey-protein",
        name: "Whey Protein Isolate",
        brand: "Momentous",
        description: "Clean, third-party-tested protein to hit your daily target and support muscle recovery.",
        price: "$60",
        link: "https://www.livemomentous.com/products/whey-protein-isolate",
        badge: "Popular",
      },
      {
        id: "electrolytes",
        name: "Electrolyte Drink Mix",
        brand: "LMNT",
        description: "Sugar-free sodium/potassium/magnesium for hydration — especially after sweat, sauna, or fasting.",
        price: "$45",
        link: "https://drinklmnt.com",
      },
    ],
  },
];

export default GEAR;
